version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - npm ci

  pre_build:
    commands:
      #- npm run cy:verify
      #- npm run cy:info
      - npm install --save-dev cypress-cucumber-preprocessor

  build:
    commands:
      #- npm run start:ci &
      #- npx cypress run --browser chromium
      - npx cypress run 

  post_build:
    commands:
      #- npm run chromium-report

artifacts:
  files:
    - 'videos/**/*'
  base-directory: 'cypress'