version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci

  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info

  build:
    commands:
      - npm run start:ci &
      - npx cypress run --browser chromium

  post_build:
    commands:
      - npm run chromium-report

artifacts:
  files:
    - 'videos/**/*'
  base-directory: 'cypress'