version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    pre_build:
    commands:
      - echo ==========  pre-build phase...  ====================
      - npm install
      - npm install --save-dev cypress-cucumber-preprocessor
      - npm --version
    build:
    commands:
      - npx cypress run
      - ls
artifacts:
  files:
    - 'cypress/videos/**/*'