version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - echo ==========  pre-build phase...  ====================
      - npm install
      - npm install --save-dev cypress-cucumber-preprocessor
      - npm --version
  build:
    commands:
      - echo ==========  build phase...  ====================
      - echo Build started on `date`
      - echo # Test execution: use -d -i options
      - npx cypress run
  post_build:
    commands:
      - echo ==========  post-build phase...  ====================
      - echo Build completed on `date`
      - pwd
      - ls
artifacts:
  files:
    - 'cypress/videos/**/*'